name: first

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   
   job1:
      name: Ubuntu job
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v4
         - name: install node
           uses: actions/setup-node@v4
           with:
              node-version: '24.15.0'
         - name: environment variables
           run: 'env | sort'
         - name: install dependencies and audit
           run: |
              npm install
              npm run build
              npm audit
   job2:
      name: Windows job
      runs-on: windows-latest
      steps:
         - name: checkout
           uses: actions/checkout@v4
         - name: install node
           uses: actions/setup-node@v4
           with:
              node-version: '24.15.0'
         - name: environment variables
           run: 'Get-ChildItem Env: | Sort-Object Name'
         - name: install dependencies and audit
           run: |
              npm install
              npm run build
              npm audit
   job3:
      name: MacOS job
      runs-on: macos-latest
      steps:
         - name: checkout
           uses: actions/checkout@v4
         - name: install node
           uses: actions/setup-node@v4
           with:
              node-version: '24.15.0'
         - name: environment variables
           run: 'env | sort'
         - name: install dependencies and audit
           run: |
              npm install
              npm run build
              npm audit
