name: Pipeline

env:
   NODE_VERSION: '24.15.0'
   PACKAGE_MANAGER: 'pnpm'
   PACKAGE_MANAGER_VERSION: '10.15.0'

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   install-and-test:
      name: install-and-test
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v4
         - name: install node
           uses: actions/setup-node@v4
           with:
              node-version: ${{ env.NODE_VERSION }}
         - name: install pnpm (package manager)
           uses: pnpm/action-setup@v4
           with:
              version: ${{ env.PACKAGE_MANAGER_VERSION }}
         - name: install dependencies, test and audit
           run: |
              pnpm install
              pnpm run test
   build-and-audit:
      name: build-and-audit
      needs: install-and-test
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v4
         - name: install node
           uses: actions/setup-node@v4
           with:
              node-version: '24.15.0'
         - name: install pnpm (package manager)
           uses: pnpm/action-setup@v4
           with:
              version: 10.15.0
         - name: install dependencies, build and audit
           run: |
              pnpm install
              pnpm run build
              pnpm audit
